project:
  type: website
  output-dir: docs

website:
  title: "Trieu Le"
  repo-actions: [edit, issue]
  navbar:
    background: "#FFFBF2"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: blog.qmd
        text: Blog


    right:
    - icon: linkedin
      href: https://www.linkedin.com/in/trieulehai/

  page-footer:
    right: "Created by Trieu Le"


format:
  html:
    theme:
      - simplex
      - custom.scss
    css: styles.css
    fontcolor: "#002642"
    backgroundcolor: "#FFFBF2"
    monobackgroundcolor: "#FAF0E3"
    toc: true

editor: visual


