project:
  type: website
  output-dir: docs

website:
  title: "Trieu Le"
  repo-url: https://github.com/uttonio/uttonio
  repo-actions: [edit, issue]
  navbar:
    background: "#FFFBF2"
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - about.qmd
    right:
    - icon: github
      href: https://github.com/trieustats
    - icon: youtube
      href: https://www.youtube.com/channel/UC9trqLDRXPvDtWUf2pDJgHw
    - icon: linkedin
      href: https://www.linkedin.com/in/trieulehai/

  page-footer:
    right: "2022, Le Hai Trieu"


format:
  html:
    theme:
      - simplex
      - custom.scss
    css: styles.css
    fontcolor: "#002642"
    backgroundcolor: "#FFFBF2"
    monobackgroundcolor: "#FAF0E3"
    toc: true



