---
title: "About me"
---

1.  I love finding out the source of any information that I read online to make sure that this information is backed by concrete research evidence and sound journalism. I am learning to be aware of the possible caveats of a fact as well.

2.  I have an older sister living in the States. She introduced to me the Americans' athletic sense as well as openness for diversity and inclusion. Living in the heart of Europe, I become very mindful of my consumption to protect the environment, and I am proud to be a minimalist. I also learn to overcome the prejudice I have as a Vietnamese girl and respect others despite differences.

3.  I love meeting people from different corners of the world, seeing their perspective about life, how they think and behave because of how they were brought up.

4.  My greatest achievement so far: I have an incredibly healthy and strong relationship with my family members.

I am on the way to be a global citizen, and I am thankful that you read my blog until this part.

Feel free to reach out to me!
